// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcWKbHoEHL78aU2UFhJdUBWTM8ts4Ap7U',
    appId: '1:105605774994:web:e45f5d33264602317b304b',
    messagingSenderId: '105605774994',
    projectId: 'fluttertest-f9d44',
    authDomain: 'fluttertest-f9d44.firebaseapp.com',
    storageBucket: 'fluttertest-f9d44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hLz-qqTO2X0XnAerZlqyh1hOdKsTXTM',
    appId: '1:105605774994:android:0126d3aec789f5797b304b',
    messagingSenderId: '105605774994',
    projectId: 'fluttertest-f9d44',
    storageBucket: 'fluttertest-f9d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1prAq1dxIHF8Gy-Zz9FJwnWjJtEj9S8',
    appId: '1:105605774994:ios:9a24240a1c2289db7b304b',
    messagingSenderId: '105605774994',
    projectId: 'fluttertest-f9d44',
    storageBucket: 'fluttertest-f9d44.appspot.com',
    iosClientId: '105605774994-t6p399lsftfius795ec34ngq7p3kdvdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc1prAq1dxIHF8Gy-Zz9FJwnWjJtEj9S8',
    appId: '1:105605774994:ios:9a24240a1c2289db7b304b',
    messagingSenderId: '105605774994',
    projectId: 'fluttertest-f9d44',
    storageBucket: 'fluttertest-f9d44.appspot.com',
    iosClientId: '105605774994-t6p399lsftfius795ec34ngq7p3kdvdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
